<a href="https://colab.research.google.com/github/Wikanes-k/multivariate/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Function

Fungtion มีส่วนสำคัญทั้งหมด 4 ส่วน

1.   บอก python ว่าเราจะเขียนฟังก์ชั่น ชื่ออะไร def function_name():  (ขาดไม่ได้)
2.   กำหนดตัวแปรที่จะเป็น input Input (ขาดได้)
3.   ส่วนประมวลผล do_something with Input to get Output (ขาดไม่ได้)
4.   ส่วน output return Output (ขาดได้)

เราใช้



``` python
def function_name(_input_):
  do_something with _Input_ to produce _output_
  return _output_
  ```


  ``` backtick กด alt -9 6

In [1]:
def print_name(name,surname,ID):
  st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'    #ต้องเว้นวรรคหน้าสุด / fต้องต่อกัน /จำคำสั่ง
  return st

การเรียกใช้ฟังชั่น

In [2]:
print_name('วิฆเนศ','เกียรติเกษมสุข','623021055-6')    #เรียกใช้คำสั่ง

'ชื่อ วิฆเนศ นามสกุล เกียรติเกษมสุข ID 623021055-6'

In [3]:
output_string = print_name('วิฆเนศ','เกียรติเกษมสุข','623021055-6')   #เรียกคำสั่งเป็นตัวหนังสือ
print(output_string)

ชื่อ วิฆเนศ นามสกุล เกียรติเกษมสุข ID 623021055-6


ฟังก์ชั่นไม่จำเป็นต้องมี output

In [4]:
def print_name2(surname,ID,name):                  
  st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
  print(st)

In [5]:
print_name2('วิฆเนศ','เกียรติเกษมสุข','623021055-6')

ชื่อ 623021055-6 นามสกุล วิฆเนศ ID เกียรติเกษมสุข


In [6]:
op2 = print_name2('วิฆเนศ','เกียรติเกษมสุข','623021055-6')

ชื่อ 623021055-6 นามสกุล วิฆเนศ ID เกียรติเกษมสุข


In [7]:
print(op2)

None


ฟังก์ชั่นไม่จำเป็นต้องมี input


In [8]:
def Pi():
  return 3.14159265359

In [9]:
#คำนวนพื้นที่วงกลมที่มีขนาดเส้นผ่านศูนย์กลางเท่ากับ 3
Pi()*(1.5**2)

7.0685834705775

In [10]:
def print_my_name():
  print('วิฆเนศ เกียรติเกษมสุข ID623021055-6')

In [11]:
print_my_name()

วิฆเนศ เกียรติเกษมสุข ID623021055-6


###1.imput ของ function ใน python มีสองแบบ input ที่จำเป็นต้องใส่ กับ input ที่ไม่จำเป็นต้องใส่ (มีค่า default)

###2.เราต้องเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน

In [12]:
def print_2line_default(name,surname,ID,grade='B'):
  st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'    #ต้องเว้นวรรคหน้าสุด / fต้องต่อกัน
  print(st)
  st2=f'เกรดวิชา Multivariate >>> {grade}'
  print(st2)

In [13]:
print_2line_default('วิฆเนศ','เกียรติเกษมสุข','623021055-6')

ชื่อ วิฆเนศ นามสกุล เกียรติเกษมสุข ID 623021055-6
เกรดวิชา Multivariate >>> B


In [14]:
print_2line_default('วิฆเนศ','เกียรติเกษมสุข','623021055-6','A')

ชื่อ วิฆเนศ นามสกุล เกียรติเกษมสุข ID 623021055-6
เกรดวิชา Multivariate >>> A


เราสามารถเรียกฟังก์ชั่นโดยใช้ชื่อตัวแปรของฟังก์ชั่นช่วยได้

In [15]:
print_name2(name='วิฆเนศ',surname='เกียรติเกษมสุข',ID='623021055-6')

ชื่อ วิฆเนศ นามสกุล เกียรติเกษมสุข ID 623021055-6


HW3 ให้เขียน function คำนวนจำนวนนาทีจาก เวลาต่อไปนี้

'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'

และ print ให้สวยงาม

In [16]:
def print_time(time):
  time_sp = time.split('-')
  answer = int(time_sp[0]) * 3600 + int(time_sp[1]) * 60 + int(time_sp[2])
  print(f'คำนวนเป็นเวลาได้เท่ากับ {answer} วินาที')

In [17]:
print_time('14-15-31')

คำนวนเป็นเวลาได้เท่ากับ 51331 วินาที


In [18]:
print_time('13-00-01')

คำนวนเป็นเวลาได้เท่ากับ 46801 วินาที


In [19]:
print_time('05-49-44')

คำนวนเป็นเวลาได้เท่ากับ 20984 วินาที


In [20]:
print_time('00-00-16')

คำนวนเป็นเวลาได้เท่ากับ 16 วินาที


Numpy -> package สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)

Num + py -> Number - Numerical + python

การใช้ package
1.   ```import``` ```ชื่อ package``` #เรียกใช้ package
2.   ```ชื่อ package.ชื่อฟังก์ชั่น``` #เรียกใช้ function



In [23]:
import numpy

data structure -> array

สร้าง array (numpy array)

In [22]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


ชี้ค่าใน numpy array

In [25]:
mat_ex1[1,1]   #[แถว,หลัก]  นับ0,1,2...

0.1

ถ้าไม่มี numpy array

In [26]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [36]:
list_ex1[1][1]

0.1

In [38]:
print(list_ex1)
a = list_ex1[1]
print(a)
print(a[1])

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


Matrix Operations

data 2 แบบ -> matrix (2D array) , scalar (ตัวเลขค่าคงที)

In [39]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2 = numpy.array([[2,3.7,5.9],[91,1.5,7.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


##บวกกับลบ matrix เอาตัวเลขเลขตำแหน่งเดียวกันมาบวกกัน

In [42]:
mat_ex0 = numpy.array([[1,2],[3,4]])
print(mat_ex0)

[[1 2]
 [3 4]]


In [41]:
mat_ex3 = mat_ex1 + mat_ex2  
print(mat_ex3)
mat_ex4 = mat_ex1 - mat_ex2 
print(mat_ex4)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  3.2  -0.7  -1.4]
 [-81.9  -1.4  -7. ]]


การตรวจสอบขนาดของ matrix  ใช้ shape

In [43]:
mat_ex3.shape

(2, 3)

In [44]:
mat_ex3.shape[0]

2

## คูณ matrix

In [48]:
mat_ex1 * mat_ex2   #คูณที่ผิด

array([[1.040e+01, 1.110e+01, 2.655e+01],
       [8.281e+02, 1.500e-01, 2.190e+00]])

##การคูณ matrix (แถวคูณหลัก)
(หลักของ Matrix ตัวข้างหน้า ต้องเท่ากับแถวของ Matrix ตัวข้างหลัง)

dot product ((AAA,x),(x,ZZZ) = (AAA,ZZZ)

In [50]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


# Transpose กลับแถวเป็นหลักกลับหลักเป็นแถว

matrix.T

In [52]:
print(mat_ex2)
print(mat_ex2.shape)

[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


In [53]:
print(mat_ex2.T)
print(mat_ex2.T.shape)

[[ 2.  91. ]
 [ 3.7  1.5]
 [ 5.9  7.3]]
(3, 2)


In [56]:
numpy.dot(mat_ex1,mat_ex2.T)  #(2,3).(3,2) = (2,2)

array([[ 48.05, 510.55],
       [ 20.34, 830.44]])

In [57]:
numpy.dot(mat_ex1.T,mat_ex2)  #(3.2).(2.3) = (3,3)

array([[838.5 ,  32.89,  97.11],
       [ 15.1 ,  11.25,  18.43],
       [ 36.3 ,  17.1 ,  28.74]])

HW4 อธิบายการหา Determinant และ Inverse matrix (รูปและคำอธิบาย)

~panda~